ecoseller/ecoseller

src/dashboard/components/Dashboard/Overview/SummaryWidget/SummaryWidget.tsx, src/dashboard/components/Dashboard/Overview/SummaryWidget/SummaryWidgetGraph.tsx, src/dashboard/components/Dashboard/Overview/SummaryWidget/SummaryWidgetGraphOrders.tsx, src/dashboard/package-lock.json, src/dashboard/package.json, src/dashboard/pages/dashboard/overview/index.tsx
Just a brief preview of possible widgets on the "homepage" of our dashboard.
It currently includes graph from cool library [apexcharts](https://apexcharts.com) and one widget-like component for viewing just single data.
=> T-39: Mock overview page

src/backend/core/category/migrations/0003_categorytranslation_description_editorjs.py, src/backend/core/category/models.py, src/backend/core/category/serializers.py, src/backend/core/category/views.py, src/backend/core/product/migrations/0020_alter_productmedia_media.py, src/backend/core/product/migrations/0022_alter_attributetype_type_name.py, src/backend/core/product/migrations/0023_alter_baseattribute_value.py, src/backend/core/product/migrations/0024_producttranslation_description_editorjs.py, src/backend/core/roles/migrations/0001_initial.py, src/backend/core/user/migrations/0002_auto_20230316_1534.py, src/backend/core/user/migrations/0003_remove_permissionrole_permissions_and_more.py, src/backend/core/user/migrations/0004_user_groups_user_is_superuser_user_user_permissions.py, src/backend/requirements.txt, src/dashboard/components/Dashboard/Catalog/Categories/List/CategoryList.tsx, src/dashboard/components/Dashboard/Generic/Forms/CategorySelectForm.tsx, src/dashboard/types/category.ts, src/dashboard/utils/category.ts
=> T-50: Category nested list

src/backend/core/product/serializers.py
closes #156 
well, I forgot to run update on all other fields except for these "nested" such as prices and attributes 😄
=> #T-156 fixed update on productvariant serializer

src/storefront/components/Footer/FooterMenu.tsx
closes #172 
@VL-CZ can you please test it? 😊
=> T-172: Fixed page overflow

src/dashboard/package-lock.json, src/dashboard/utils/context/permission.tsx, src/dashboard/utils/context/user.tsx
Functionality implemented:
* Permission context provider
Demo with dummy data example - wont be merged:
https://user-images.githubusercontent.com/61156764/235183514-1e3902a6-4c2d-4360-9e7f-c6e9e327a5f9.mov
=> [T-170] Permission context provider

src/backend/.gitignore, src/backend/core/product/serializers.py, src/backend/docker-compose.env, src/dashboard/components/Dashboard/Catalog/Products/Editor/ProductEditorWrapper.tsx, src/dashboard/pages/api/product/[id].ts
https://github.com/ecoseller/ecoseller/assets/34132752/447affc9-9cb7-4468-b304-7dfe06792c4c
well, I did not believe I'll ever get here, but after few attemps, I finally managed to cherry-pick one commit from the first PR, so hopefully I did not break our 👶 into pieces.
=> #T-234: Product delete (vol3)

src/recommender_system/app/recommender_system/managers/prediction_pipeline.py, src/recommender_system/app/recommender_system/models/prediction/dummy/model.py, src/recommender_system/app/recommender_system/models/prediction/popularity/model.py, src/recommender_system/app/recommender_system/models/prediction/selection/model.py, src/recommender_system/app/recommender_system/models/prediction/similarity/model.py, src/recommender_system/app/recommender_system/models/prediction/similarity/tools.py, src/recommender_system/app/recommender_system/models/stored/base.py, src/recommender_system/app/recommender_system/models/stored/feedback/base.py, src/recommender_system/app/recommender_system/models/stored/model/base.py, src/recommender_system/app/recommender_system/models/stored/model/trainer_queue_item.py, src/recommender_system/app/recommender_system/models/stored/product/base.py, src/recommender_system/app/recommender_system/models/stored/product/order.py, src/recommender_system/app/recommender_system/models/stored/similarity/base.py, src/recommender_system/app/recommender_system/scripts/fill_data.py, src/recommender_system/app/recommender_system/server/container.py, src/recommender_system/app/recommender_system/storage/abstract.py, src/recommender_system/app/recommender_system/storage/feedback/abstract.py, src/recommender_system/app/recommender_system/storage/feedback/storage.py, src/recommender_system/app/recommender_system/storage/model/abstract.py, src/recommender_system/app/recommender_system/storage/model/storage.py, src/recommender_system/app/recommender_system/storage/product/abstract.py, src/recommender_system/app/recommender_system/storage/product/statistics.py, src/recommender_system/app/recommender_system/storage/product/storage.py, src/recommender_system/app/recommender_system/storage/similarity/abstract.py, src/recommender_system/app/recommender_system/storage/similarity/storage.py, src/recommender_system/app/recommender_system/storage/sql/storage.py, src/recommender_system/app/run_migrate.sh
I split the storage functionality so only the needed operations for each storage is available
=> [T-204] Storage refactor

src/recommender_system/app/recommender_system/scripts/fill_data.py
It is now finally possible to import feedback data from Retailrocket dataset to database to use them to train models of level 3 and 4.
=> [T-191] Feedback data import from Retailrocket dataset implemented

src/backend/core/cart/models.py, src/backend/core/cart/serializers.py, src/backend/core/cart/urls.py, src/backend/core/cart/views.py, src/storefront/api/cart/methods.ts, src/storefront/components/Cart/Methods/PaymentMethodList.tsx, src/storefront/components/Cart/Methods/ShippingMethodList.tsx, src/storefront/components/Cart/Methods/ShippingPaymentMethodItem.tsx, src/storefront/pages/api/cart/[token]/detail.ts, src/storefront/pages/api/cart/[token]/payment-method/[id].ts, src/storefront/pages/api/cart/[token]/payment-method/index.ts, src/storefront/pages/api/cart/[token]/shipping-method/[id].ts, src/storefront/pages/api/cart/[token]/shipping-method/index.ts, src/storefront/pages/api/cart/methods/[country].ts, src/storefront/pages/cart/step/2.tsx, src/storefront/types/cart.ts
Implemented "step 2" of the cart - shipping / payment method setter with GUI.
It works pretty much like this:
1. Data are fetched from the server (list of shipping methods with nested list of allowed payment methods and selected shipping/payment methods based on cart token)
2. If cart has some methods assigned, they're prefilled
3. If user has some payment method selected and they select new shipping method and selected payment method is not allowed for given shipping method, payment method is reseted
etc.
https://github.com/ecoseller/ecoseller/assets/34132752/30e59e4b-bed1-4f2c-ae38-0467d6a7f600
close #42
=> [T-42]: Shipping and Payment setter in cart

src/backend/core/cart/views.py, src/backend/core/category/views.py, src/backend/core/cms/views.py, src/backend/core/country/views.py, src/backend/core/order/views.py, src/backend/core/product/views.py, src/backend/core/roles/decorator.py, src/backend/core/roles/views.py, src/backend/core/user/views.py
Hey,
this isnt a big one, but a tricky one. I checked that decorator is working correctly (e.g. only if user has is_staff flag set it can access view), but I wasnt able to check every single view (as it would probably took me like 2 weeks of testing). So please, @michalpulpan  and @VL-CZ check parts that you are familiar with and ensure that decorator is only on top of **bashboard** GET views. Thank you <3
=> [T-254] Decorator for checking is_staff on dashboard GET views

src/dashboard/components/Dashboard/Order/Detail/OrderDetailMethod.tsx, src/dashboard/utils/imgPath.ts, src/storefront/components/Cart/Methods/ShippingPaymentMethodItem.tsx, src/storefront/utils/imgPath.ts
Just a quick PR, fixed an issue with img path. 
Now, it should work both in & outside container 🙂
=> [H-4] Fixed image paths

src/docker-compose.yaml, src/storefront/components/ProductDetail/MediaGallery.tsx, src/storefront/next.config.js, src/storefront/pages/product/[id]/[slug].tsx
Sorry, accidentally pushed a bug on storefront product page in #216
=> [H-7] fixed unserializable country and hardcoded pricelist

src/recommender_system/Dockerfile
@matejscerba 
So, now I'm officialy a RS contributor 😄
I made this small change in your Dockerfile that saves us a ton of time while rebuilding the images (that's because of Docker caching - see [here](https://docs.docker.com/build/cache/#how-can-i-use-the-cache-efficiently))
Basically, before if you made any change in RS code and rebuilt the image, the dependencies would be reinstalled again (which takes ~ 10 minutes ⏳).
Now, the dependencies will be reinstalled **only if you change** the requirements file (which doesn't happen that often, right?). So, if you don't change requirements, the rebuild is much faster, now it takes just seconds 🙂
=> [H-8] RS Dockerfile optimization

src/storefront/styles/Slider/Slider.module.scss
=> [H-9] Fixed homepage slider width

src/backend/requirements.txt
=> [H-10]: wrong python requirements

src/backend/core/cart/migrations/0026_rename_unit_price_gross_cartitem_unit_price_incl_vat_and_more.py
Fixed conflicts in migrations, so our backend now starts successfully 😊
=> [H-12] migrations conflicts fixed

src/storefront/components/Common/CookieDisclaimer.tsx, src/storefront/components/Footer/FooterLine.tsx, src/storefront/pages/_app.tsx, src/storefront/styles/Common/CookieDisclaimer.module.scss, src/storefront/utils/context/cookies.tsx
Implemented cookie provider (to set & parse cookie of cookie preferences 😄 ) and cookie disclaimer (modal that is shown to user with no cookie preferences 😊 ).
See demo and the cookie itself - if it's readable 😃 .
This PR actually implement #211  and #210 (but #210 wasn't created and I made it as one task - it was easier for debugging 😊 )
https://github.com/ecoseller/ecoseller/assets/34132752/e67e0bcd-c540-45c5-af3f-745064792220
=> [T-211]: Cookie provider + Cookie disclaimer

src/backend/core/user/views.py, src/storefront/components/Header/Icons/User.tsx, src/storefront/pages/user/detail/index.tsx, src/storefront/utils/context/user.tsx
* Fixed problem where accessToken wasnt refreshed after its expiration
* Fixed not fetching general info about user right after login and redirect to "Profile" page
=> [H-13] User context provider fix + general info fetch fix

src/backend/core/cart/models.py, src/backend/core/order/views.py, src/storefront/components/Cart/CartItemList.tsx, src/storefront/components/Cart/CartOrderSummary.tsx, src/storefront/components/Category/ProductCard.tsx, src/storefront/components/Common/OrdersList.tsx, src/storefront/components/Generic/DiscountText.tsx, src/storefront/components/Order/OrderDetails.tsx, src/storefront/components/Review/AverageRating.tsx, src/storefront/components/Review/RatingsList.tsx, src/storefront/pages/cart/index.tsx, src/storefront/pages/cart/summary.tsx, src/storefront/pages/order/[orderId]/index.tsx, src/storefront/pages/user/orders/index.tsx, src/storefront/pages/user/register/index.tsx, src/storefront/public/locales/cs/common.json, src/storefront/public/locales/cs/order.json, src/storefront/public/locales/en/cart.json, src/storefront/public/locales/en/common.json, src/storefront/public/locales/en/order.json, src/storefront/types/order.ts
https://github.com/ecoseller/ecoseller/assets/30175078/7267521e-8cb0-4c0b-b656-0645fc4bcc80
Implemented order detail page on storefront.
It's mostly the same as cart summary (the page before payment)
=> [T-326] Order detail - Storefront

src/backend/core/cart/views.py, src/backend/core/category/views.py, src/backend/core/core/settings.py, src/backend/core/core/urls.py, src/backend/core/country/views.py, src/backend/core/order/views.py, src/backend/core/product/views.py, src/backend/core/review/views.py, src/backend/core/roles/views.py, src/backend/core/search/views.py, src/backend/core/user/views.py, src/dashboard/pages/dashboard/catalog/categories/add.tsx
- endpoint `/swagger/`
- added brief documentation to all views that haven't been documented yet
https://github.com/ecoseller/ecoseller/assets/30175078/57447ca2-54fb-4cbb-a5a1-a5f110a11730
Note that many views (basically all for dashboard) require authentication token, so naturally these requests via Swagger UI fail with 401/403
=> [T-25] Add OpenAPI

src/recommender_system/app/recommender_system/managers/cache_manager.py, src/recommender_system/app/recommender_system/managers/prediction_pipeline.py, src/recommender_system/app/recommender_system/server/container.py, src/recommender_system/app/recommender_system/storage/cache/abstract.py, src/recommender_system/app/recommender_system/storage/cache/storage.py
`PredictionPipeline.run` has inconsistent return types because I am finishing connecting RS to the rest of the application
=> [T-80] Cache manager implemented

src/backend/core/recommender/views.py, src/dashboard/components/Dashboard/CMS/Categories/List/PageCategoryTypeListTopLine.tsx, src/storefront/components/Common/ProductsSlider.tsx, src/storefront/pages/cart/index.tsx, src/storefront/pages/index.tsx, src/storefront/pages/product/[id]/[slug].tsx, src/storefront/utils/context/recommender.tsx
Finished implementation of serializing recommended products in `core` and their presentation in the `storefront`.
Now you know my preferred movies ;)
=> [H-35]: Fetching recommended products from core

src/backend/core/product/views.py
This PR fixes the following bug:
> Ahoj, všiml jsem si, že při úpravě produktu na dashboardu ten produkt zmizí ze seznamu catalog/products. Podíval byste se na to někdo, prosím?
> jo aha :joy: on se zařadí na konec.. je tam asi řazení dle updated_at… nebylo by lepsi ID?
=> [H-42] sort products by ID
